# -*- coding: utf-8 -*-
"""BST FP Kelompok 17.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KpYC2mciwJJjKQbdUdoXXk_slE839KSK
"""

#import library
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

#import drive
from google.colab import drive
drive.mount('/content/drive')

#load data

dbs = pd.read_csv('/content/drive/MyDrive/FP BST/vending_machine_sales.csv', sep=',', engine='python')

dbs

category_MQty = dbs.groupby('Category')['MQty'].sum()

plt.figure(figsize=(10, 6))
category_MQty.plot(kind='bar')
plt.xlabel('Kategori')
plt.ylabel('Jumlah Transaksi')
plt.title('Jumlah Transaksi per Kategori')
plt.xticks(rotation=0)
plt.tight_layout()

plt.show()

lokasi_transaksi = dbs['Location'].value_counts()

# Buat bar chart
plt.figure(figsize=(10, 6))
lokasi_transaksi.plot(kind='bar')
plt.xlabel('Lokasi')
plt.ylabel('Jumlah Transaksi')
plt.title('Perbandingan Jumlah Transaksi di Setiap Lokasi')
plt.xticks(rotation=0)
plt.tight_layout()

# Tampilkan plot
plt.show()

avg_mesin = dbs.groupby('Machine')['TransTotal'].mean()

plt.figure(figsize=(10, 6))
avg_mesin.plot(kind='bar')
plt.xlabel('Jenis Mesin')
plt.ylabel('Rata-rata Total Transaksi')
plt.title('Rata-rata Total Transaksi di Setiap Jenis Mesin')
plt.xticks(rotation=0)
plt.tight_layout()

avg_type = dbs.groupby('Type')['TransTotal'].mean()

plt.figure(figsize=(10, 6))
avg_type.plot(kind='bar')
plt.xlabel('Jenis Mesin')
plt.ylabel('Rata-rata Total Transaksi')
plt.title('Rata-rata Total Transaksi di Setiap Jenis Mesin')
plt.xticks(rotation=0)
plt.tight_layout()